name: Build

on: [push]

env:
  TOOLCHAIN: cruel
  INSTALLER: yes

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        model: [ "N971N" ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: sudo apt-get install -y -qq libtinfo5 ccache unzip wget

      - name: Disable compression in ccache
        run: |
          ccache -o compression=false
          ccache -o cache_dir=$HOME/.ccache

      - name: Get current date
        id: get_date
        run: |
          echo "FULL_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "MONTH_DATE=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Create cache key
        id: model_key
        run: |
          echo "KEY=$(echo '${{ matrix.model }}' | tr ',' '_')" >> $GITHUB_OUTPUT

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ccache-${{ env.TOOLCHAIN }}-${{ steps.model_key.outputs.KEY }}-${{ steps.get_date.outputs.FULL_DATE }}
          restore-keys: |
            ccache-${{ env.TOOLCHAIN }}-${{ steps.model_key.outputs.KEY }}-${{ steps.get_date.outputs.MONTH_DATE }}
            ccache-${{ env.TOOLCHAIN }}-${{ steps.model_key.outputs.KEY }}-
            ccache-${{ env.TOOLCHAIN }}-

      - name: Kernel Configure
        run: |
          set -e
          ./cruelbuild config \
            model=${{ matrix.model }} \
            name=NetHunterKernel \
            toolchain=$TOOLCHAIN \
            +magisk \
            +hid_gadget \
            +usb_configfs \
            +mass_storage \
            +ath9k_htc \
            +rtl88xxau \
            +wireguard \
            +overclock \
            +schedutil \
            +1000hz \
            +cifs \
            +nethunter \
            +morosound \
            +boeffla_wl_blocker | tee config.info

      - name: Install gcc-aarch64-linux-gnu
        if: env.TOOLCHAIN == 'system-gcc' || env.TOOLCHAIN == 'system-clang'
        run: sudo apt-get install -y -qq gcc-aarch64-linux-gnu

      - name: Install clang
        if: env.TOOLCHAIN == 'system-clang'
        run: sudo apt-get install -y -qq llvm lld clang

      - name: Clone Toolchain
        if: env.TOOLCHAIN != 'system-gcc' && env.TOOLCHAIN != 'system-clang'
        run: |
          git clone --depth 1 -j$(nproc) --branch $TOOLCHAIN \
            --single-branch https://github.com/CruelKernel/samsung-exynos9820-toolchain toolchain

      - name: Build Kernel
        run: ./cruelbuild :build

      - name: Install mkbootimg
        run: |
          wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py gki
          chmod +x mkbootimg.py
          sudo mv mkbootimg.py /usr/local/bin/mkbootimg
          sudo mv gki $(python3 -c 'import site; print(site.getsitepackages()[0])')

      - name: Install mkdtboimg
        run: |
          wget -q https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/master.tar.gz -O - | tar --strip-components 2 -xzf - utils/src/mkdtboimg.py
          chmod +x mkdtboimg.py
          sudo mv mkdtboimg.py /usr/local/bin/mkdtboimg

      - name: Install avbtool
        run: |
          wget -q https://android.googlesource.com/platform/external/avb/+archive/refs/heads/master.tar.gz -O - | tar xzf - avbtool.py
          chmod +x avbtool.py
          sudo mv avbtool.py /usr/local/bin/avbtool

      - name: Create Kernel Image
        run: ./cruelbuild :mkimg

      - name: Create Installer
        if: env.INSTALLER == 'yes'
        run: ./cruelbuild :pack

      - name: Unzip Installer
        if: env.INSTALLER == 'yes'
        run: |
          mkdir -p installer && cd installer
          unzip ../CruelKernel.zip

      - name: Upload Kernel Zip
        if: env.INSTALLER == 'yes'
        uses: actions/upload-artifact@v3
        with:
          name: CruelKernel-${{ matrix.model }}
          path: installer/*
          if-no-files-found: error

      - name: Upload Kernel Images
        if: env.INSTALLER != 'yes'
        uses: actions/upload-artifact@v3
        with:
          name: CruelKernel-${{ matrix.model }}
          path: '*.img'
          if-no-files-found: error

      - name: Upload Kernel Config
        uses: actions/upload-artifact@v3
        with:
          name: ConfigurationInfo-${{ matrix.model }}
          path: config.*
          if-no-files-found: error
